<a href="https://colab.research.google.com/github/Wipada6430205202/data_warehouse/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_02_Python101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python Coding 🐍

In [ ]:
print ("My first Python code!")
print ("Python is easier than I expected!!!")

My first Python code!
Python is easier than I expected!!!


To check your Python version and other extensions' version

In [ ]:
!python --version

Python 3.10.12


In [ ]:
!pip install --upgrade version_information
%load_ext version_information
%version_information numpy, scipy, matplotlib, sympy, version_information

  Preparing metadata (setup.py) ... done
  Created wheel for version_information: filename=version_information-1.0.4-py3-none-any.whl size=3894 sha256=3ed6da977ffb0c31683a2821c20e09fd8b5d4da351edfd4f63482c4e3c57b7a9
  Stored in directory: /root/.cache/pip/wheels/81/48/43/91109adffe66267dfa0c5c27c05269409bc131d850c0fd386b
Successfully built version_information


Software versions
Python 3.10.12 64bit [GCC 11.4.0]
IPython 7.34.0
OS Linux 5.15.109+ x86_64 with glibc2.35
numpy 1.23.5
scipy 1.10.1
matplotlib 3.7.1
sympy 1.12
version_information 1.0.4
Thu Sep 07 03:31:44 2023 UTC

To install this IPython extension

In [ ]:
# you only need to do this once
!pip install --upgrade version_information

You may sometimes encounter this error. \
`ModuleNotFoundError: No module named 'pandas' in Python`

If you cannot import due to your computer cannot find, try installing the library using `pip install <library-name>`.

Begin the line with `!` to direct your code to command line

In [ ]:
!pip install pandas

Help with functions

In [ ]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [ ]:
print(abs.__doc__)

Return the absolute value of the argument.


## Variables

ข้อกำหนดในการตั้งชื่อตัวแปร

* ชื่อห้ามมีเว้นวรรค
* (พยายาม)ใช้ภาษาอังกฤษ
* ตัวเล็กกับตัวใหญ่ แตกต่างกัน (case sensitive)
* ห้ามใช้ตัวเลขเป็นตัวหน้า

In [ ]:
variable_a = 12
variable_b = 3.14
variable_c = "1" # ' (quote) หรือ " (double quote)
variable_d = 'Learning Pandas'
variable_e = True
variable_f = None

In [ ]:
variable_ab = variable_a + variable_b
print(variable_ab)

15.14


In [ ]:
print(type(variable_a))
print(type(variable_b))
print(type(variable_c))
print(type(variable_d))
print(type(variable_e))
print(type(variable_f))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'NoneType'>


Use functions: `int()`, `float()`, `str()`, `list()`, `tuple()`, `set()`, `complex()`, `ord()`, `hex()`, `oct()`, `dict()`, etc. to change type of object (type casting) in Python

In [ ]:
print( float(variable_c), type(float(variable_c)) )

1.0 <class 'float'>


In [ ]:
print(variable_c, type(variable_c))
new_c = int(variable_c)
print(new_c, type(new_c))

1 <class 'str'>
1 <class 'int'>


In [ ]:
variable_g = 1

In [ ]:
x = 8
X = 1e-02
x == X

False

In [ ]:
y =1

## Operations

| Operator | Operation | Example |
|---|---|---|
| + | Addition | 5 + 2 = 7 |
| - | Subtraction | 4 - 2 = 2 |
| * | Multiplication | 2 * 3 = 6 |
| / | Division | 4 / 2 = 2 |
| // | Floor Division | 10 // 3 = 3 |
| % | Modulo | 5 % 2 = 1 |
| ** | Power | 4 ** 2 = 16 |

In [ ]:
print(-1, 2+3, 7%3, 7/2, 7//2, 2**4)

-1 5 1 3.5 3 16


![order of operations](https://s3.amazonaws.com/cloudxlab/static/images/course/python-foundation-course/pemdas.png)

In [ ]:
43 + 13 - 9 / 3 * 7

35.0

| Operator | Name | Example |
|---|---|---|
| = | Assignment Operator | a = 7 |
| += | Addition Assignment | a += 1 # a = a + 1 |
| -= | Subtraction Assignment | a -= 3 # a = a - 3 |
| *= | Multiplication Assignment | a *= 4 # a = a * 4 |
| /= | Division Assignment | a /= 3 # a = a / 3 |
| %= | Remainder Assignment | a %= 10 # a = a % 10 |
| **= | Exponent Assignment | a **= 10 # a = a ** 10 |

In [ ]:
a = 10
b = 5

In [ ]:
a += b      # a = a + b
print(a)

15


In [ ]:
a *= b #a = a * b
print(a)

75


| Operator | Meaning | Example |
| --- | --- | --- |
| == | Is Equal To | 3 == 5 results in False |
| != | Not Equal To | 3 != 5 results in True |
| > | Greater Than | 3 > 5 results in False |
| < | Less Than | 3 < 5 results in True |
| >= | Greater Than or Equal To | 3 >= 5 results in False |
| <= | Less Than or Equal To | 3 <= 5 results in True |

In [ ]:
print(3 <= 4, 3 == 4, 3 != 4, 3 > 4)

True False True False


In [ ]:
True == 1

True

In [ ]:
False == 0

True

In [ ]:
2 == 2.000000

True

In [ ]:
2 == 2.0000000000000000001

True

In [ ]:
2 == 2.001

False

In [ ]:
import math
help(math.isclose)

Help on built-in function isclose in module math:

isclose(a, b, *, rel_tol=1e-09, abs_tol=0.0)
    Determine whether two floating point numbers are close in value.
    
      rel_tol
        maximum difference for being considered "close", relative to the
        magnitude of the input values
      abs_tol
        maximum difference for being considered "close", regardless of the
        magnitude of the input values
    
    Return True if a is close in value to b, and False otherwise.
    
    For the values to be considered close, the difference between them
    must be smaller than at least one of the tolerances.
    
    -inf, inf and NaN behave similarly to the IEEE 754 Standard.  That
    is, NaN is not close to anything, even itself.  inf and -inf are
    only close to themselves.



In [ ]:
math.isclose(2, 2.001, rel_tol=1e-03)

True

| Operator | Example | Meaning |
|---|---|---|
| and | a and b | True only if both the operands are True |
| or | a or b | True if at least one of the operands is True |
| not | not a | True if the operand is False and vice-versa |
| is | x is True | True if the operands are identical |
| is not | x is not True | True if the operands are not identical |
| in | 5 in x | True if value/variable is found in the sequence |
| not in | 5 not in x | True if value/variable is not found in the sequence |

In [ ]:
print(True and True, False or True)

True True


`x = 10` (0000 1010 in binary) and `y = 4` (0000 0100 in binary)

| Operator | Meaning | Example |
| --- | --- | --- |
| & | Bitwise AND | x & y = 0 (0000 0000) |
| \| | Bitwise OR | x \| y = 14 (0000 1110) |
| ~ | Bitwise NOT | ~x = -11 (1111 0101) |
| ^ | Bitwise XOR | x ^ y = 14 (0000 1110) |
| >> | Bitwise right shift | x >> 2 = 2 (0000 0010) |
| << | Bitwise left shift | x << 2 = 40 (0010 1000) |

In [ ]:
print(True & False, True | False)

False True


## Containers (Collections)

In [ ]:
a_tuple = (1, 2, 3, 4)
a_list = ['a', 'b', 'c', 'd']
a_set = {1, 2, 2, 3, 3, 3}
a_dict = {'c': 1, 'b': 2, 'a': 3}

### Tuple

In [ ]:
print("The length of a_tuple:", a_tuple, "is", len(a_tuple))

The length of a_tuple: (1, 2, 3, 4) is 4


Access element in tuple or list using the name of tuple or list variable following by *square brackets* <p>
<center>`tuple_or_list_var[index]`</center>

* Index starts with zero
* Final feasible index is (length - 1)
* Negative index reverses the position from -1 to -(length)

In [ ]:
print("a_tuple:", a_tuple)
print("values in each index", a_tuple[0], a_tuple[1], a_tuple[2], a_tuple[3])
print("values in each reverse index", a_tuple[-1], a_tuple[-2], a_tuple[-3], a_tuple[-4])
print("length of a_tuple", len(a_tuple))
print(a_tuple[len(a_tuple)])

a_tuple: (1, 2, 3, 4)
values in each index 1 2 3 4
values in each reverse index 4 3 2 1
length of a_tuple 4


IndexError: ignored

<font color='red'><h4>📝 Your turn</h4></font>
```[ข้อความลิงก์](https:// [ข้อความลิงก์](https://))
myTuple = (12,123,12,12,1)
```
Get the element `123` from `myTuple`


In [ ]:
myTuple = (12,123,123,12,1)
myTuple

(1, 12, 123, 1234, 12, 1)

In [ ]:
# Get the element 123 from myTuple
myTuple[1]

123

In [ ]:
# Last element
myTuple[4]
myTuple[-1]

1

<font color='red'><h4>📝 Your turn</h4></font>
```[ข้อความลิงก์](https:// [ข้อความลิงก์](https://))
myTuple = (12,123,1234,12,1)
```
Get the element `123` from `myTuple`


In [ ]:
myTuple = (12,123,1234,12,1)
myTuple

(12, 123, 1234, 12, 1)

In [ ]:
# Get the element 123 from myTuple
myTuple[1]

123

In [ ]:
# Last element
myTuple[4]
myTuple[-1]

1

### List

Working with list is similar to tuple

In [ ]:
print("a_list:", a_list)

a_list: ['a', 'b', 'c', 'd']


In [ ]:
len(a_list)

4

In [ ]:
a_list[0]

'a'

In [ ]:
a_list[-1]

'd'

In [ ]:
a_list.index('b')

1

To display multiple elements:
* Using `list[i:j]` to display element i$^\text{th}$ to (j-1)$^\text{th}$

In [ ]:
a_list[1:3] # return 1-2

['b', 'c']

* Iterating over a list

In [ ]:
[a_list[i] for i in [0,2]]

['a', 'c']

Adding an element to a list

In [ ]:
a_list.append('e') #เติมค่า
a_list

['a', 'b', 'c', 'd', 'e']

Adding two lists concatenates them together

In [ ]:
a_list + a_list

['a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e']

In [ ]:
a_list + ['u', 'i']

['a', 'b', 'c', 'd', 'e', 'u', 'i']

Multiplying a list with an integer `n` creates a repeatation of a list `n` times

In [ ]:
[1,3]*3 # copy ตัวนั้น

[1, 3, 1, 3, 1, 3]

String is a list of characters. Therefore, working with string is similar to list.

In [ ]:
variable_d

'Learning Pandas'

In [ ]:
print(variable_d[0])
print(variable_d[1:8])
print(variable_d[1:(variable_d.index('g')+1)])
print(variable_d[-1])
print(variable_d[1:])

L
earning
earning
s
earning Pandas


In [ ]:
print(variable_d[:8])

Learning


In [ ]:
variable_d[0:2]

'Le'

In [ ]:
'Keep ' + variable_d

'Keep Learning Pandas'

<font color='red'><h4>📝 Your turn</h4></font>
```
variable_d = "Learning Pandas"
```


In [ ]:
variable_f = "Walking a corgi in the park"

In [ ]:
variable_f [10:15]

'corgi'

In [ ]:
# get the character "P" from variable_d
variable_d[9]
Pindex = variable_d.index("P")
Pindex
variable_d[Pindex]

'P'

In [ ]:
# get the word "Pandas" from variable_d
variable_d[9:]
variable_d[9:15]


'Pandas'

#### Advance list slicing
* Using [start_index:end_index:step]

In [ ]:
variable_d

'Learning Pandas'

In [ ]:
variable_d[::]

'Learning Pandas'

In [ ]:
variable_d[::2] # display using step of 2

'Lann ads'

In [ ]:
variable_d[::-1] # reversing a list

'sadnaP gninraeL'

* `range(start_value, final_value, step)`

In [ ]:
range(0,4)

range(0, 4)

In [ ]:
list(range(0,4))

[0, 1, 2, 3]

In [ ]:
list(range(1,5,1))

[1, 2, 3, 4]

In [ ]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

* `range(n)` = `range(0, n, 1)`

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

`map(func, *iterables)` --> Make an iterator that computes the function using arguments from each of the iterables.  Stops when the shortest iterable is exhausted.

In [ ]:
list(map(lambda x: x**2, range(5)))

[0, 1, 4, 9, 16]

### Set

In [ ]:
a_set = {1, 2, 2, 3, 3, 3}
print("a_set = {1, 2, 2, 3, 3, 3}")
print("a_set:", a_set)

a_set = {1, 2, 2, 3, 3, 3}
a_set: {1, 2, 3}


In [ ]:
len(a_set)

6

Casting set ot list

In [ ]:
list(a_set)

[1, 2, 2, 3, 3, 3]

In [ ]:
list(a_set)[0]

1

### Dict

Python dictionary stores data in key-value format

In [ ]:
a_dict = {'c': 1, 'b': 2, 'a': 3}
print("a_dict = {'c': 1, 'b': 2, 'a': 3}")
print("a_dict:", a_dict)

a_dict = {'c': 1, 'b': 2, 'a': 3}
a_dict: {'c': 1, 'b': 2, 'a': 3}


In [ ]:
a_dict.keys()

dict_keys(['c', 'b', 'a'])

In [ ]:
a_dict.values()

dict_values([1, 2, 3])

In [ ]:
len(a_dict)

3

In [ ]:
a_dict.items()

dict_items([('c', 1), ('b', 2), ('a', 3)])

In [ ]:
for key,val in a_dict.items():
    print("key of", key, "gives value of", val)

key of c gives value of 1
key of b gives value of 2
key of a gives value of 3


In [ ]:
a_dict['c']

1

In [ ]:
a_dict['a']

3

In [ ]:
# add key "d" with value "4" to a_dict
a_dict["d"] = 4
a_dict

{'c': 1, 'b': 2, 'a': 3, 'd': 4}

<font color='red'><h4>📝 Your turn</h4></font>
<p>Create a dictionary from the following lists

```
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
```

In [ ]:
# create my_dict
my_dict = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
my_dict['Twenty']

20

In [ ]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
print("zip(keys,values):", zip(keys, values))
print("convert zip(keys,values) to list:", list(zip(keys, values)))
my_dict1 = dict(zip(keys, values))
my_dict1

zip(keys,values): <zip object at 0x7cfa581dd240>
convert zip(keys,values) to list: [('Ten', 10), ('Twenty', 20), ('Thirty', 30)]


{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

In [ ]:
my_dict2 = {}
for i in range(len(keys)):
  my_dict2[keys[i]] = values[i]
my_dict2

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

## Vectors and Arrays

In [ ]:
import numpy as np # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (ในรูปแบบ matrix)

Create numpy array

In [ ]:
np_a = np.array([[1,2,3],[4,5,6]])
np_a

array([[1, 2, 3],
       [4, 5, 6]])

The size of a matrix can be accessed using `matrix.shape` resulting in (#rows,#columns)

In [ ]:
np_a.shape

(2, 3)

In [ ]:
np_a.shape[0]

2

In [ ]:
n_rows,n_cols = np_a.shape
print(n_rows, n_cols)

2 3


In [ ]:
np_b = np.array([[1,4],[2,5],[3,6]])
print(np_b.shape)
np_b

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.random.randn(3,2)

array([[-0.14829133,  0.4616874 ],
       [-0.54535265, -0.64913188],
       [-0.09044369, -0.48112219]])

In [ ]:
np.random.randint(0, 10, (3,2)) # random integers from 0 to 9

array([[7, 8],
       [1, 6],
       [2, 2]])

Indexing: [row,column] where using `:` as index means to select all elements in rows or columns

In [ ]:
print(np_b)
np_b[0,1]

[[1 4]
 [2 5]
 [3 6]]


4

<font color='red'><h4>📝 Your turn</h4></font>

Retrieve the element `3` from `np_b`

In [ ]:
# Retrieve the element 3 from np_b
np_b[2,0]


3

In [ ]:
np_b[1]

array([2, 5])

In [ ]:
np_b[1, :]

array([2, 5])

In [ ]:
np_b[1:3, 1:]

array([[5],
       [6]])

Transpose matrix

In [ ]:
np_b.T

array([[1, 2, 3],
       [4, 5, 6]])

matrix multiplication

In [ ]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.dot(np_b,np_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [ ]:
np.dot(np_a,np_b)

array([[14, 32],
       [32, 77]])

In [ ]:
np_a * np_b

ValueError: ignored

In [ ]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_a * np_a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
np_a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
np_a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

Useful numpy functions

In [ ]:
print(np_a)
np.sum(np_a)

[[1 2 3]
 [4 5 6]]


21

In [ ]:
np.sum(np_a, axis=0)

array([5, 7, 9])

In [ ]:
np.sum(np_a, axis=1)

array([ 6, 15])

In [ ]:
np.mean(np_a)

3.5

In [ ]:
np.mean(np_a, axis=0) # compute mean along the row axes

array([2.5, 3.5, 4.5])

In [ ]:
np.mean(np_a, axis=1) # compute mean along the column axes

array([2., 5.])

In [ ]:
np_a.max(axis=0)

array([4, 5, 6])

## Pandas Series
One-dimensional ndarray with axis labels \
https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series

In [ ]:
import pandas as pd

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}
diet = pd.Series(calories)
#myseries = pd.Series([420, 380, 390], index=["day1","day2","day3"])
diet

day1    420
day2    380
day3    390
dtype: int64

In [ ]:
diet["day2"]

380

In [ ]:
diet[0]

420

In [ ]:
diet.mean()

396.6666666666667

## Pandas Dataframe
Two-dimensional tabular data \
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame

### Creating a dataframe

![createDF](https://pbpython.com/images/pandas-dataframe-shadow.png)

In [ ]:
import pandas as pd

In [ ]:
!pip install pandas-profiling

In [ ]:
from pandas_profiling import ProfileReport

<ipython-input-101-e2a33329b6f0>:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport


In [ ]:
d = {'No': [1, 2, 3, 4, 5],
     'Name': ["สมบูรณ์", "สมชาย", "สมหญิง", "สมหมาย", "สมบัติ"],
     'Age': [23, 45, 62, 30, 32]}
df = pd.DataFrame(data = d)
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.columns
#list(df.columns)

Index(['No', 'Name', 'Age'], dtype='object')

In [ ]:
df.index
#list(df.index)

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   No      5 non-null      int64 
 1   Name    5 non-null      object
 2   Age     5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes


In [ ]:
df.head()
#df.tail()

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [ ]:
df.describe()

No        Age
count  5.000000   5.000000
mean   3.000000  38.400000
std    1.581139  15.404545
min    1.000000  23.000000
25%    2.000000  30.000000
50%    3.000000  32.000000
75%    4.000000  45.000000
max    5.000000  62.000000

In [ ]:
df.describe(include='all')

No     Name        Age
count   5.000000        5   5.000000
unique       NaN        5        NaN
top          NaN  สมบูรณ์        NaN
freq         NaN        1        NaN
mean    3.000000      NaN  38.400000
std     1.581139      NaN  15.404545
min     1.000000      NaN  23.000000
25%     2.000000      NaN  30.000000
50%     3.000000      NaN  32.000000
75%     4.000000      NaN  45.000000
max     5.000000      NaN  62.000000

### Selecting data

In [ ]:
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [ ]:
df["Name"]

0    สมบูรณ์
1      สมชาย
2     สมหญิง
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

In [ ]:
df[["Name"]]

Name
0  สมบูรณ์
1    สมชาย
2   สมหญิง
3   สมหมาย
4   สมบัติ

In [ ]:
df[["Name", "Age"]]

Name  Age
0  สมบูรณ์   23
1    สมชาย   45
2   สมหญิง   62
3   สมหมาย   30
4   สมบัติ   32

In [ ]:
df["Name"]
#type(df["Name"]) # pandas.core.series.Series

0    สมบูรณ์
1      สมชาย
2     สมหญิง
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

![ilocvsloc](https://sparkbyexamples.com/wp-content/uploads/2021/10/pandas-difference-loc-vs-iloc.png)

In [ ]:
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [ ]:
df.iloc[1,2]

45

In [ ]:
df.iloc[2,2]

62

In [ ]:
df.loc[df['Age']>40,:]

No    Name  Age
1   2   สมชาย   45
2   3  สมหญิง   62

In [ ]:
df[df['Age']>40]

No    Name  Age
1   2   สมชาย   45
2   3  สมหญิง   62

In [ ]:
df["Name"]=="สมหมาย"

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [ ]:
df.loc[df["Name"]=="สมหมาย",:]
#df.loc[df["Name"]=="สมหมาย"]

No    Name  Age
3   4  สมหมาย   30

<font color='red'><h4>📝 Your turn</h4></font>

In [ ]:
# Retrieve "สมหญิง" from df
df.iloc[2,1]
df.loc[df["Name"]=="สมหญิง","Name"]
df.loc[df["Name"]=="สมหญิง"]["Name"]

2    สมหญิง
Name: Name, dtype: object

In [ ]:
# Get "Name" of people in df whose "Age" are less than 40 year's old
df.loc[df["Age"]<40,"Name"]




0    สมบูรณ์
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

## Controlling program flow

### Condition: if-elif-else

In [ ]:
'a' if 3 < 4 else 'b'

'a'

In [ ]:
'a' if 4 < 3 else 'b'

'b'

```python
if เงื่อนที่เราจะตรวจสอบ (โดยอาศัยสัญลักษณ์เหล่านี้ ==, !=, <, >, <=, >=, in, is_null()) :
    ถ้าเงื่อนไขเป็นจริง ทำ
```

In [ ]:
if 1 < 5:
    print('yes')

yes


```python
if เงื่อนไขที่จะตรวจสอบ (โดยใช้สัญลักษณ์ ==,!=,<,>,<=,>=):
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ 1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ 2
elif เงื่อนไขที่จะตรวจสอบต่อไปถ้าเงื่อนไขข้างบนไม่เป็นจริง:
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ a1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ a2
elif เงื่อนไขที่จะตรวจสอบต่อไปถ้าเงื่อนไขข้างบนไม่เป็นจริง:
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ b1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ b2
else: #ตรวจสอบเงื่อนไขข้างบนแล้วไม่เป็นจริง
    ทำงานที่ X
```
Note: จะไม่ `elif` หรือไม่มีก็ได้

In [ ]:
import numpy as np

# random a real number between 60 to 100
score = np.random.uniform(60, 100)
print("score =", np.round(score,2))

if score > 90:
    print('A')
elif score > 80:
    print('B')
else:
    print('C')

score = 83.22
B


### Loop: for
```python
for ตัวแปรที่เราจะรับค่าจากลิสต์ in ลิสต์ที่ต้องการจะวนลูป:
    do something
    do another thing
this is outside the loop
```
Note: indent using 4 spaces

In [ ]:
food = ['chiken', 'shabu', 'vegetable']

In [ ]:
for i in food:
    print("I like to eat", i)

I like to eat chiken
I like to eat shabu
I like to eat vegetable


In [ ]:
for i in range(10, 20, 2):
    print(i, i**2)

10 100
12 144
14 196
16 256
18 324


In [ ]:
xs = []
for x in range(5):
    if x % 2 == 0:
        xs.append(x)
xs

[0, 2, 4]

Using `for` loop to create a list

In [ ]:
[x**2 for x in range(5)]

[0, 1, 4, 9, 16]

In [ ]:
[x**2 for x in range(5) if x % 2 == 0]

[0, 4, 16]

In [ ]:
[x**2 if x % 2 == 0 else -1 for x in range(5)]

[0, -1, 4, -1, 16]

### Loop: for, while
```python
while true_condition:
    do something
```
Note: indent using 4 spaces

In [ ]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    count += 1

0
1
2
3
4


In [ ]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    # break while loop if count = 3
    if count == 3:
        break
    count += 1

0
1
2
3


### Function
```python
def ชื่อฟังก์ชั่น(input1,input2,....):
    do something
    do another thing
    return output
```

In [ ]:
# Hello
# """
# Hello, my name is Meow!
# Hi!
# """

In [ ]:
def f(x):
    """Say something about the function here."""
    return x

In [ ]:
f("Hello Pythonions!")

'Hello Pythonions!'

In [ ]:
f(3.14)

3.14

In [ ]:
def compute_sum(a, b):
    """Calculate the sum of a and b."""
    return a + b

In [ ]:
compute_sum(3,4)

7

In [ ]:
def h(a= 0 , b = 1, c = 2):
    """Cacluates some complicated mathematical function."""
    return a + 2*b + 3*c

In [ ]:
h()

8

In [ ]:
h(1,1,2)

9

In [ ]:
h(a=1)

9

In [ ]:
h(c=3,b=2,a=1)

14

In [ ]:
def func1(s):
    """
    Print a string 's' and tell how many characters it has
    s: a given string
    """
    print(s + " has " + str(len(s)) + " characters")

In [ ]:
func1("Hello!")

Hello! has 6 characters


In [ ]:
help(func1)

Help on function func1 in module __main__:

func1(s)
    Print a string 's' and tell how many characters it has
    s: a given string



## Using libraries

### math library

In [ ]:
import math
math.pi

3.141592653589793

In [ ]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [ ]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [ ]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [ ]:
math.log(math.e)

1.0

In [ ]:
math.log(4)

1.3862943611198906

In [ ]:
math.log(4, 2)

2.0

### numpy library

In [ ]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
from numpy.random import rand
rand(4)

array([0.27369929, 0.06689894, 0.42373462, 0.73348517])

- Some other very useful modules form the Python standard library are `os`, `sys`, `shutil`, `re`, etc.
- A complete lists of standard modules for Python 3 is available at http://docs.python.org/3/library/